apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: fastapi-app-build
spec:
  source:
    type: Git
    git:
      uri: https://github.com/your-user/your-fastapi-repo.git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: fastapi-app:latest
